project:
  type: website
  output-dir: docs

website:
  title: "Jordan Y. Aljbour"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research & Publications
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true